import { useMemo, useState, useRef } from "react";
import { extractCustomRules, summarizeRule } from "../generator/xml-parser";

interface Props {
  customRules: string[];
  onSetCustomRules: (rules: string[]) => void;
  onClearCustomRules: () => void;
}

export function CustomRulesStep({ customRules, onSetCustomRules, onClearCustomRules }: Props) {
  const [message, setMessage] = useState<string | null>(null);
  const [messageIsError, setMessageIsError] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Display highest-priority first (matching in-game top-to-bottom order)
  const summaries = useMemo(
    () => customRules.map((r, i) => ({ ...summarizeRule(r), index: i })).reverse(),
    [customRules]
  );

  const handleImport = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setMessage(null);
    const reader = new FileReader();
    reader.onload = () => {
      try {
        const rules = extractCustomRules(reader.result as string);
        if (rules.length === 0) {
          setMessage(
            "No custom rules found. Make sure the XML was generated by FilterStaff and you added rules between the sentinel markers."
          );
          setMessageIsError(true);
        } else {
          onSetCustomRules(rules);
          setMessage(`Imported ${rules.length} custom rule${rules.length > 1 ? "s" : ""}.`);
          setMessageIsError(false);
        }
      } catch (err) {
        setMessage(
          `Failed to parse XML: ${err instanceof Error ? err.message : "unknown error"}`
        );
        setMessageIsError(true);
      }
    };
    reader.readAsText(file);
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  const handleDelete = (index: number) => {
    onSetCustomRules(customRules.filter((_, i) => i !== index));
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}>
      <section>
        <h3 style={{ marginBottom: "0.5rem" }}>Custom Rules</h3>
        <p style={{ fontSize: "0.8rem", color: "var(--text-secondary)", marginBottom: "0.5rem" }}>
          Import custom rules from a previously generated XML. Rules you added
          in-game between the sentinel markers will be preserved across
          regenerations.
        </p>
        <div style={{ display: "flex", gap: "0.75rem", flexWrap: "wrap" }}>
          <label style={{ ...btnSecondary, cursor: "pointer" }}>
            Import from XML
            <input
              ref={fileInputRef}
              type="file"
              accept=".xml"
              onChange={handleImport}
              style={{ display: "none" }}
            />
          </label>
          {customRules.length > 0 && (
            <button onClick={onClearCustomRules} style={btnSecondary}>
              Clear All ({customRules.length})
            </button>
          )}
        </div>
        {message && (
          <div
            style={{
              marginTop: "0.5rem",
              color: messageIsError ? "var(--bad-color)" : "var(--accent)",
              fontSize: "0.8rem",
            }}
          >
            {message}
          </div>
        )}
      </section>

      {summaries.length > 0 && (
        <section>
          <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
            {summaries.map((s) => (
              <div
                key={s.index}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "0.75rem",
                  padding: "0.75rem 1rem",
                  background: "var(--bg-secondary)",
                  border: "1px solid var(--border)",
                  borderRadius: 6,
                  fontSize: "0.85rem",
                }}
              >
                <span
                  style={{
                    fontWeight: 600,
                    color: s.type === "HIDE" ? "var(--bad-color)" : "var(--accent)",
                    minWidth: 42,
                  }}
                >
                  {s.type}
                </span>
                <span style={{ flex: 1, color: "var(--text-primary)" }}>
                  {s.name || <span style={{ color: "var(--text-secondary)", fontStyle: "italic" }}>(unnamed)</span>}
                  <span style={{ color: "var(--text-secondary)", marginLeft: "0.5rem", fontSize: "0.8rem" }}>
                    {formatConditions(s.conditionTypes, s.affixCount, s.equipmentTypes)}
                  </span>
                </span>
                {!s.enabled && (
                  <span style={{ fontSize: "0.75rem", color: "var(--text-secondary)" }}>disabled</span>
                )}
                <span style={{ fontSize: "0.75rem", color: "var(--text-secondary)" }}>
                  #{s.index + 1}
                </span>
                <button
                  onClick={() => handleDelete(s.index)}
                  style={{
                    background: "none",
                    border: "none",
                    color: "var(--text-secondary)",
                    cursor: "pointer",
                    padding: "0.25rem 0.5rem",
                    borderRadius: 4,
                    fontSize: "0.8rem",
                  }}
                  title="Remove this custom rule"
                >
                  X
                </button>
              </div>
            ))}
          </div>
        </section>
      )}

      {summaries.length === 0 && (
        <p style={{ color: "var(--text-secondary)", fontSize: "0.85rem" }}>
          No custom rules stored. Generate a filter, add rules in-game between the
          "CUSTOM RULES START/END" markers, then import the XML here.
        </p>
      )}
    </div>
  );
}

function formatConditions(types: string[], affixCount: number, equipmentTypes: string[]): string {
  const parts: string[] = [];
  if (types.includes("AffixCondition")) parts.push(`${affixCount} affix${affixCount !== 1 ? "es" : ""}`);
  if (types.includes("SubTypeCondition") && equipmentTypes.length > 0) parts.push(equipmentTypes.join(", "));
  if (types.includes("RarityCondition")) parts.push("rarity");
  if (types.includes("ClassCondition")) parts.push("class");
  if (types.includes("PotentialCondition")) parts.push("LP/WW");
  if (types.includes("CorruptionCondition")) parts.push("corrupted");
  if (types.includes("CharacterLevelCondition")) parts.push("level");
  if (parts.length === 0 && types.length === 0) return "no conditions";
  return parts.join(" + ");
}

const btnBase: React.CSSProperties = {
  padding: "0.75rem 2rem",
  border: "none",
  borderRadius: 6,
  fontSize: "1rem",
  fontWeight: 600,
  cursor: "pointer",
  display: "inline-flex",
  alignItems: "center",
};

const btnSecondary: React.CSSProperties = {
  ...btnBase,
  background: "var(--bg-secondary)",
  color: "var(--text-primary)",
  border: "1px solid var(--border)",
};
